vanna-ai/vanna

src/vanna/base/base.py
read local/remote url dynamically in connect_to_sqlite
=> read local/remote url dynamically in connect_to_sqlite

src/vanna/ZhipuAI/ZhipuAI_Chat.py, src/vanna/ZhipuAI/ZhipuAI_embeddings.py, src/vanna/base/base.py, src/vanna/chromadb/chromadb_vector.py
Sometimes we don't need visualize the data. And by saving the token usage when we are testing some question, it's wise to close the visualize the data.
=> add a visualize parm for the ask function

src/vanna/chromadb/chromadb_vector.py
I verified that the method `reomove_collection` with typo was not used elsewhere in Vanna.
Hence, this renaming should not affect the rest of the framework (see [here](https://github.com/search?q=repo%3Avanna-ai%2Fvanna%20reomove_collection&type=code)).
=> Minor refactoring in ChromaDB class; renamed method; added description to method

src/vanna/__init__.py
This is a tiny PR only affecting one statement in the `__rpc_call()` method.
The if statement logic starts with a not, which IMO does not make much sense and makes the code harder to read.
I have corrected for this.
=> Refactored if statement in __rpc_call to improve readability

src/vanna/base/base.py
The setup is a bit complicated to describe in full. In summary, I loaded the [Chinook dataset](https://github.com/lerocha/chinook-database) into my database, then followed the [guide](https://vanna.ai/docs/postgres-openai-standard-chromadb.html) for getting setup with OpenAI and Postgres quite closely.
Before the code change
```python
vn.ask(question="which employee has the most customers?")
```
```text
None
```
After
```python
vn.ask(question="which employee has the most customers?")
```
```text
('SELECT support_rep_id, COUNT(customer_id) AS customer_count\nFROM customer\nGROUP BY support_rep_id\nORDER BY customer_count DESC\nLIMIT 1;',
support_rep_id  customer_count
0               3              21,
None)
```
=> Return sql and dataframe if call is successful

training_data/sample-salaries/questions.json
There are some typos in questions.json, please look into it and correct accordingly (if any)
Thanks.
=> Update some spellings in questions.json

src/vanna/openai/openai_chat.py
max_tokens wasn't getting set if you passed in an OpenAI client
=> Fix the max tokens bug

src/vanna/base/base.py
1. Pass `initial_prompt` as parameter in config of VannaBase with default as `None` which redirects to using the existing initial prompt as input.
=> Make initial prompt used in get_sql_prompt() a passable parameter

src/vanna/flask/__init__.py
When using the flask app using the new option `allow_llm_to_see_data=False`, followup questions are not generated, which becomes a problem when reloading the question as followup questions are required in cache for the function `load_question`, which throws an error:  
Cache an empty array for followup questions with `allow_llm_to_see_data=False` option
=> fix(flask): no followup questions error

src/vanna/ZhipuAI/ZhipuAI_Chat.py, src/vanna/ZhipuAI/__init__.py, src/vanna/anthropic/__init__.py, src/vanna/chromadb/__init__.py, src/vanna/marqo/__init__.py, src/vanna/marqo/marqo.py, src/vanna/mistral/__init__.py, src/vanna/ollama/__init__.py, src/vanna/ollama/ollama.py, src/vanna/openai/__init__.py, src/vanna/vannadb/__init__.py
As observed in https://github.com/vanna-ai/vanna/pull/259#issuecomment-2027242687, some classes like `Ollama` can not be accessed as wanted.
Currently, to access it, the user would need to write:
```
from vanna.ollama.ollama import Ollama
```
But the ideal behaviour is:
```
from vanna.ollama import Ollama
```
**This PR adds support to allow both (with and without smart import shortcut).**
I added the same to some other relevant submodules such as `Mistral`, `Anthropic`, `OpenAI`, `ZhipuAI`.
---
EDIT: I also now added the same to the vector DB classes, such as `MarqoDB`, `VannaDB`, and `ChromaDB`.
=> Added smart import shortcuts for some submodules

src/vanna/openai/openai_chat.py
Fixes #332.
Seems to work fine. I did a small test below to verify that setting the `model` with this new API works, but I was unable to run tests. Not sure why. Are you able to test and verify that it runs fine, @zainhoda?
I set the model explicitly when running `generate_sql` like so:
```
sql = vn_openai.generate_sql("What are the top 4 customers by sales?", model="gpt-4")
```
To test that it works I just added two prints into the code itself (not included in PR, just for testing):
Console showing that the model is set and passed appropriately to the completion call:
=> Allow to set `model` for separate `submit_prompt` calls to OpenAI

src/vanna/base/base.py
Fixes https://github.com/vanna-ai/vanna/issues/315.
Changes:
=> Add support for setting number of follow-up questions

src/vanna/ZhipuAI/ZhipuAI_Chat.py, src/vanna/base/base.py, src/vanna/flask/__init__.py, src/vanna/remote.py, src/vanna/vannadb/vannadb_vector.py
This PR adds two sql extraction methods:
1 - Extract SQL query from non-markdown responses, extracting the query between `SELECT` and `;`
2 - Extract SQL query containing CTE (WITH clause), extracting the query between `WITH` and `;`
Also it removes the f-string from strings with no placeholders (like `f"Hello World"`)
=> Add sql extraction in case of non-markdown response or CTE

src/vanna/base/base.py
If Vanna is running on a microservice (for example FastAPI) it can happen that the service is not running for more than 4 hours so Snowflake Token expires.
This happens when the app runs "connect_to_snowflake" at the application startup.
I would suggest to make the connection always active until the service is running otherwise the service will fail.
=> [Scalabrese] Added client_session_keep_alive = True to Snowflake

src/vanna/exceptions/__init__.py
The exceptions defined in vanna.exceptions can not be catched with a `try: ... except Exception as e:`.  
```python
from vanna.exceptions import ValidationError
try:
raise ValidationError()
except Exception as e:
print("Caught with Exception")
try:
raise ValidationError()
except BaseException as e:
print("Caught with BaseException")
```
Vanna exceptions are all derived from the class `BaseException` instead of the class `Exception`.
```python
class ValidationError(BaseException):
class Exception(BaseException):
class BaseException(object):
```
Therefore, they cannot be catched with `try: ... except Exception as e:` ([BaseException Documentation](https://docs.python.org/3.12/library/exceptions.html#BaseException)).
Define Exception as the parent class of all Vanna Exceptions instead of …
=> fix: exceptions not caught with `except Exception as e:`

src/vanna/base/base.py
**old version:**
```python
dialect = "SQL"
initial_prompt = f"You are a {dialect} expert. "
"Please help to generate a SQL query to answer the question. Your response should ONLY be based on the given context and follow the response guidelines and format instructions. "
print(initial_prompt)
```
terminal ouput:
```log
You are a SQL expert.
```
**new version:**
```python
dialect = "SQL"
initial_prompt = f"You are a {dialect} expert. " + \
"Please help to generate a SQL query to answer the question. Your response should ONLY be based on the given context and follow the response guidelines and format instructions. "
print(initial_prompt)
```
terminal ouput:
```log
You are a SQL expert. Please help to generate a SQL query to answer the question. Your response should ONLY be based on the given …
```
=> Fix string concatenation in initial_prompt

src/vanna/vllm/vllm.py
Added support for hosted LLM using vLLM
Changes made:
- Introduced `auth-key` configuration option to Vllm class
- Modified `__init__` method to handle `auth-key` configuration
- Updated `submit_prompt` method to include `Authorization` header if `auth-key` is provided
=> Add auth-key support and validation to vLLM

src/vanna/qdrant/qdrant.py
Return `True` if successful deletion of training data.
Previous version returned `None`.
=> Fix qdrant `remove_training_data` api

src/vanna/base/base.py
Allowed the user to easily set the maximum prompt context length when configuring vanna
=> Allow user to specify max prompt length

src/vanna/flask/__init__.py
related to #428 
When no graph is generated, retrieving a converstation through the history fails as the cache is expecting a `fig_json` field.  
The following error is displayed: 
set fig_json as an optional field instead of a required one for the function `VannaFlaskApp.load_question`. The conversation is then displayed, followed by an empty graph:  
It would be good to take into account the possibility of `fig` being null in the JS displaying the graph so that it shows nothing instead of an epty graph, but as it is in the assets I can't modify it.
=> fix(flask): missing fig_json error

src/vanna/base/base.py
**Optimize the usage of `title` in the `log` function within `base.py`:**
I noticed that the `title` variable in the log function is not actually used. For example:
```python
def log(self, message: str, title: str = "Info"):
print(message)
```
```python
self.log(title="LLM Response", message=llm_response)
```
**Add the parameter allow_llm_to_see_data=False to the ask function:**
When I ran my code, the terminal displayed the following message:
```log
The LLM is not allowed to see the data in your database. Your question requires database introspection to generate the necessary SQL. Please set allow_llm_to_see_data=True to enable this.
```
I checked the parameters of the `ask` function to add this parameter but found that the `ask` function does not have this parameter. 
Instead, this …
=> Two optimizations: log and allow_llm_to_see_data

src/vanna/qdrant/qdrant.py
`UpdateStatus` can be either `acknowledged` or `completed`. Either means successful deletion
=> Qdrant - Return `True` on successful deletion

src/vanna/qdrant/qdrant.py
Fixes #464 by initializing `id_suffixes` after affirming collection names.
=> fix: Qdrant id_suffixes when using custom collection names

src/vanna/flask/__init__.py
An error occurs when redraw figure is executed：
`UnboundLocalError: local variable 'code' referenced before assignment`
The bug is fixed by this commit.
=> fix: draw figure bug

src/vanna/base/base.py
**Pull Request Description:**
This pull request addresses an issue in the `extract_sql` function where the regex used to extract SQL queries from LLM responses incorrectly matches the keyword "WITHIN". This results in incomplete and invalid SQL queries being extracted. The regex has been updated to use word boundaries to ensure accurate matching of the "WITH" keyword at the start of CTEs. This fix resolves the syntax errors encountered when running the extracted SQL queries.
**Related Previous Pull Requests:**
- [#350](https://github.com/vanna-ai/vanna/pull/350/commits/9482713be05bc60546a55a35d9c34ca585b28cdd)
- [#377](https://github.com/vanna-ai/vanna/pull/377/files/1bec99ad938fc1246f36f7990c955a2ceec51a62)
**Issue:**
When a response contains a SQL query with the keyword "WITHIN", the …
=> Fix regex in `extract_sql` to correctly handle SQL containing CTEs (without matching WITHIN)

src/vanna/hf/hf.py
Hi Guys, Here's my pull request discussed in #502 . I have added quantization support for huggingface models and have changed a variable 'model_name' to 'model_name_or_path' as transformers can load models from checkpoint files in local directory.
=> Added quantization support for huggingface models

src/vanna/google/gemini_chat.py
The current `GoogleGeminiChat` does not respect `model_name` when authenticating without api-key.
This is a one-liner fix.
=> fix: model name for gemini chat is hardcoded when no api-key is used

src/vanna/anthropic/anthropic_chat.py
This is a minor change. Right now, if an Anthropic client is passed into VannaBase, an error is thrown due to the fact that `self.temperature` doesn't exist. This shifts around some conditionals in the `__init__()` to resemble what's occurring in the `OpenAI_Chat` class, which fixes the problem.
=> Fix anthropic_chat.py - self.temperature doesn't exist if an Anthropic client is passed into VannaBase

training_data/sample-fraud/questions.json
=> chore: update questions.json

src/vanna/openai/openai_chat.py
In vanna, `max_tokens` is used to control the size of the prompt that is generated from the user question. This should be sufficiently large (defaults to 14k)
In openai, `max_tokens` defines the maximum length of the generated output (max. ca. 5k). This should be controlled by a different parameter (if at all)
=> Remove max_tokens from openai_chat.py

src/vanna/qdrant/qdrant.py
This PR updates the Qdrant integration to use the new [Query API](https://qdrant.tech/blog/qdrant-1.10.x/) that supersedes the search API.
=> refactor: Use Qdrant's Query API

src/vanna/vllm/vllm.py
Added temperature support for hosted LLM using vLLM
Changes made:
* Introduced default temperature of 0.7 in __init__ method
* Updated JSON payload in submit_prompt method to include temperature
This change allows users to control the randomness of the model's output.  If not specified, it defaults to 0.7, providing a balance between creativity and coherence in the generated text.
=> Add temperature support to vLLM

src/vanna/ollama/ollama.py, src/vanna/remote.py
json.dumps without ensure_ascii=False will print unicode char which is not convinient to read.
=> Prompt Content not print unicode char

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Vanna Guru](https://gurubase.io/g/vanna) to Gurubase. Vanna Guru uses the data from this repo and data from the [docs](https://vanna.ai/docs/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Vanna Guru", which highlights that Vanna now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable …
=> Introducing Vanna Guru on Gurubase.io

src/vanna/cohere/__init__.py, src/vanna/cohere/cohere_chat.py, src/vanna/cohere/cohere_embeddings.py, tests/test_imports.py, tests/test_vanna.py
- Introduced Cohere_Chat class for chat interactions with customizable parameters.
- Added Cohere_Embeddings class for generating embeddings with a default model.
- Updated imports in test files to include new classes and added tests for Cohere functionality.
=> Add Cohere integration with Cohere_Chat and Cohere_Embeddings classes
