- .github/workflows/tests.yml
- .gitignore
- src/vanna/__init__.py
- src/vanna/exceptions.py
- src/vanna/utils.py
- tests/test_files/sql/testSqlCreate.sql
- tests/test_files/sql/testSqlSelect.sql
- tests/test_files/training/questions.json
- tests/test_vanna.py
- Addressed https://github.com/vanna-ai/vanna-py/issues/22
- Handled errors with custom excpetion classes
- Replaced print statements with logger.info
- Did some code formating
- Added test cases
> Make vn.train generic

- README.md
https://github.com/vanna-ai/vanna/issues/92
> Add "Contributing" into the README.md

- .github/workflows/tests.yml
- .gitignore
- README.md
- pyproject.toml
- tox.ini
> Use `tox` in GH action

- .pre-commit-config.yaml
- setup.cfg
Closes https://github.com/vanna-ai/vanna/issues/95
> Add pre-commit hook

- src/vanna/__init__.py
Closes https://github.com/vanna-ai/vanna/issues/77
> Replace ddl parameter with sql

- src/vanna/__init__.py
MISC should be using `question` instead of `Question` to display the correct message.
> MISC should be using `question` instead of `Question` to display the correct message.

- src/vanna/openai/openai_chat.py
- src/vanna/openai/openai_embeddings.py
Fixes #262.
I also did some minor refactoring - removed redundant imports and cleaned up the code, both manually and according to pre-commit hook suggestions.
> Adds support for setting max_tokens and temperature in OpenAI Chat

- src/vanna/chromadb/chromadb_vector.py
Fixed #218.
CC: @zainhoda, @philippschw
> Add support for setting number of retrieved similar sql queries in chroma

- pyproject.toml
- src/vanna/opensearch/__init__.py
- src/vanna/opensearch/opensearch_vector.py
- tests/test_imports.py
https://github.com/vanna-ai/vanna/issues/388
> feat:add OpenSearch vector database to be supportted

- src/vanna/qdrant/qdrant.py
> fix: String format qdrant

- src/vanna/base/base.py
> feat:add support presto

- src/vanna/qdrant/qdrant.py
Was not able to delete particular ID from training data (qdrant db)
> Qdrant delete ID from training data minor mistake

- pyproject.toml
- src/vanna/base/base.py
- Implemented a new feature to support connection and querying to ClickHouse databases.
- Updated the database configuration files to include ClickHouse as an option.
> feat: Add ClickHouse connection and query support

- src/vanna/base/base.py
hive and kyuubi to be supportted
> feat:add hive and kyuubi to be supportted

- src/vanna/opensearch/opensearch_vector.py
OpenSearch buglist:
https://github.com/opensearch-project/OpenSearch/issues/10802 
https://github.com/opensearch-project/OpenSearch/issues/10747
> fix: json_parse_exception bug by set http_compress=False default 

- pyproject.toml
- src/vanna/base/base.py
Using clickhouse_connect instead of clickhouse_driver, works way better.
>  feat: Add ClickHouse connection via clickhouse_connect

- src/vanna/base/base.py
add reconnect mysql if the connection is closed
> add reconnect mysql if the connection is closed

- src/vanna/flask/__init__.py
Vanna AI can adapt itself to any front-end,  but it can also be deployed as an API. The class `VannaFlaskApp` is arleady itself an API, which is consumed by the JS frontend described in the assets. 
This PR extracts the API endpoints and put them in a class named `VannaFlaskAPI`. `VannaFlaskApp` is then defined as `class VannaFlaskApp(VannaFlaskAPI)`.  
I think this would make it clearer for users that the Flask App can be used for its API, and could lead to interesting evolutions (example: documentation in OpenAPI format, appearance of other open-source apps consuming the API)
> Split VannaFlaskApp into an API and full app

- src/vanna/flask/__init__.py
Iterating on the idea raised in #508, this PR adds a Swagger documentation of the Flask API using [Flasgger](https://github.com/flasgger/flasgger). It creates a Swagger app on the endpoint (/apidocs) which looks like this:
doc is also available as a json file at `/apispec_1.json`.  
So far, the doc is stored in the docstring of each endpoint function. If it comes as an issue, it could be stored in many different ways:
- with one file per function, files being located in a dir `src/vanna/flask/apispec/` and applied to each endpoint function with the decorator `@swag_from` (ex: `@swag_from("src/vanna/flask/apispec/get_config.yml")`)
- as a single json file, by exporting the file at the endpoint `/apispec_1.json` into a file at `src/vanna/flask/apispec.json`
> Document Flask API with Swagger

- src/vanna/base/base.py
Sometimes the output SQL is wrong and cannot be executed. Reduce the problem.
> feat: add  Validate the syntax of the output SQL to ensure it is correct and executable.

- src/vanna/base/base.py
#548 
Add support for additional db connect options across all `connect_to_*` adapters.
> #548: Added support for additional db connect options.

- src/vanna/ollama/ollama.py
default ollama.client timeout is 240.0, i change it as param ollama_timeout. when not set ollama_timeout param. default ollama timeut is 240.
> add ollama_timeout param

- src/vanna/qianwen/QianwenAI_chat.py
- src/vanna/qianwen/QianwenAI_embeddings.py
- src/vanna/qianwen/__init__.py
- QianwenAI chat
- QianwenAI embedding
> <feat><QianwenAI>add QianwenAI call function

- src/vanna/faiss/__init__.py
- src/vanna/faiss/faiss.py
This pull request introduces the integration of FAISS (Facebook AI Similarity Search) into VannaAI to enable efficient and scalable vector-based search.
> Integrating FAISS in VannaAI

- src/vanna/azuresearch/azuresearch_vector.py
As in the flask application keyword argument was passing as question not text
> text to question parameter in the get_similar_question_sql(azure search)

- src/vanna/google/gemini_chat.py
This PR changes the version from 1.0 to 1.5 and also uses the **general available** version of the `GenerativeModel` class from the SDK.
> Update Gemini version and SDK

- papers/ai-sql-accuracy-2023-08-17.md
The relevance search is depicted in a green box, not a red box.
> Fixed typo in ai-sql-accuracy-2023-08-17.md

- src/vanna/base/base.py
- src/vanna/opensearch/opensearch_vector.py
- src/vanna/types/__init__.py
> Revert "【feat】add database engine and table name to support table ddl update"
